Repository Sage/carbon-codemod, pull requests merged in 2020-10, with the labels that each got.

#28 feat: add universal replace-prop and remove-prop codemods
  README.md
  bin/__tests__/carbon-codemod.js
  bin/cli.js
  transforms/remove-prop/README.md
  transforms/remove-prop/__testfixtures__/Basic.input.js
  transforms/remove-prop/__testfixtures__/Basic.output.js
  transforms/remove-prop/__testfixtures__/Bug.input.js
  transforms/remove-prop/__testfixtures__/Bug.output.js
  transforms/remove-prop/__testfixtures__/NoImport.input.js
  transforms/remove-prop/__testfixtures__/NoImport.output.js
  transforms/remove-prop/__tests__/remove-prop.js
  transforms/remove-prop/remove-prop.js
  transforms/rename-prop/README.md
  transforms/rename-prop/__testfixtures__/Basic.input.js
  transforms/rename-prop/__testfixtures__/Basic.output.js
  transforms/rename-prop/__testfixtures__/Bug.input.js
  transforms/rename-prop/__testfixtures__/Bug.output.js
  transforms/rename-prop/__testfixtures__/NoImport.input.js
  transforms/rename-prop/__testfixtures__/NoImport.output.js
  transforms/rename-prop/__tests__/rename-prop.js
  transforms/rename-prop/rename-prop.js
Labels: enhancement

#29 feat: tile padding prop codemod
  README.md
  bin/cli.js
  transforms/builder/finder.js
  transforms/builder/index.js
  transforms/builder/removeAttribute.js
  transforms/builder/renameAttribute.js
  transforms/builder/replaceAttributeValue.js
  transforms/builder/run.js
  transforms/replace-prop-value/README.md
  transforms/replace-prop-value/__testfixtures__/NoImport.input.js
  transforms/replace-prop-value/__testfixtures__/NoImport.output.js
  transforms/replace-prop-value/__testfixtures__/NumberStringNewValue.input.js
  transforms/replace-prop-value/__testfixtures__/NumberStringNewValue.output.js
  transforms/replace-prop-value/__testfixtures__/NumberStringOldValue.input.js
  transforms/replace-prop-value/__testfixtures__/NumberStringOldValue.output.js
  transforms/replace-prop-value/__testfixtures__/NumberToNumber.input.js
  transforms/replace-prop-value/__testfixtures__/NumberToNumber.output.js
  transforms/replace-prop-value/__testfixtures__/NumberToString.input.js
  transforms/replace-prop-value/__testfixtures__/NumberToString.output.js
  transforms/replace-prop-value/__testfixtures__/StringToNumber.input.js
  transforms/replace-prop-value/__testfixtures__/StringToNumber.output.js
  transforms/replace-prop-value/__testfixtures__/StringToString.input.js
  transforms/replace-prop-value/__testfixtures__/StringToString.output.js
  transforms/replace-prop-value/__tests__/replace-prop-value.js
  transforms/replace-prop-value/replace-prop-value.js
  transforms/tile-update-padding-prop/README.md
  transforms/tile-update-padding-prop/__testfixtures__/Basic.input.js
  transforms/tile-update-padding-prop/__testfixtures__/Basic.output.js
  transforms/tile-update-padding-prop/__testfixtures__/Bug.input.js
  transforms/tile-update-padding-prop/__testfixtures__/Bug.output.js
  transforms/tile-update-padding-prop/__testfixtures__/NoImport.input.js
  transforms/tile-update-padding-prop/__testfixtures__/NoImport.output.js
  transforms/tile-update-padding-prop/__tests__/tile-update-padding-prop.js
  transforms/tile-update-padding-prop/tile-update-padding-prop.js
Labels: No QA Required, No UX QA Required, Passed Review, Squad Front End

#30 feat(dialog-full-screen): add appwrapper to wrap children
  README.md
  bin/cli.js
  transforms/dialog-full-screen-app-wrapper/README.md
  transforms/dialog-full-screen-app-wrapper/__testfixtures__/AlreadyHasAppWrapper.input.js
  transforms/dialog-full-screen-app-wrapper/__testfixtures__/AlreadyHasAppWrapper.output.js
  transforms/dialog-full-screen-app-wrapper/__testfixtures__/Basic.input.js
  transforms/dialog-full-screen-app-wrapper/__testfixtures__/Basic.output.js
  transforms/dialog-full-screen-app-wrapper/__testfixtures__/MultipleDialogFullScreens.input.js
  transforms/dialog-full-screen-app-wrapper/__testfixtures__/MultipleDialogFullScreens.output.js
  transforms/dialog-full-screen-app-wrapper/__testfixtures__/NestedDialogFullScreen.input.js
  transforms/dialog-full-screen-app-wrapper/__testfixtures__/NestedDialogFullScreen.output.js
  transforms/dialog-full-screen-app-wrapper/__testfixtures__/NoImport.input.js
  transforms/dialog-full-screen-app-wrapper/__testfixtures__/NoImport.output.js
  transforms/dialog-full-screen-app-wrapper/__testfixtures__/SelfClosedDialogFullScreen.input.js
  transforms/dialog-full-screen-app-wrapper/__testfixtures__/SelfClosedDialogFullScreen.output.js
  transforms/dialog-full-screen-app-wrapper/__testfixtures__/WithChildrenAsAnExpressionContainerWithAppWrapper.input.js
  transforms/dialog-full-screen-app-wrapper/__testfixtures__/WithChildrenAsAnExpressionContainerWithAppWrapper.output.js
  transforms/dialog-full-screen-app-wrapper/__testfixtures__/WithChildrenAsAnExpressionContainerWithNoAppWrapper.input.js
  transforms/dialog-full-screen-app-wrapper/__testfixtures__/WithChildrenAsAnExpressionContainerWithNoAppWrapper.output.js
  transforms/dialog-full-screen-app-wrapper/__testfixtures__/WithChildrenAsFunctionDeclaration.input.js
  transforms/dialog-full-screen-app-wrapper/__testfixtures__/WithChildrenAsFunctionDeclaration.output.js
  transforms/dialog-full-screen-app-wrapper/__testfixtures__/WithDifferentImportIdentifier.input.js
  transforms/dialog-full-screen-app-wrapper/__testfixtures__/WithDifferentImportIdentifier.output.js
  transforms/dialog-full-screen-app-wrapper/__testfixtures__/WithMultipleChildrenAsExpressionContainers.input.js
  transforms/dialog-full-screen-app-wrapper/__testfixtures__/WithMultipleChildrenAsExpressionContainers.output.js
  transforms/dialog-full-screen-app-wrapper/__tests__/dialog-full-screen-app-wrapper-test.js
  transforms/dialog-full-screen-app-wrapper/dialog-full-screen-app-wrapper.js
Labels: No UX QA Required, Passed Review, Pending QA, Squad Front End
